@startuml Activity
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

(*) -> "m"
-> "Queue"
if "Extract Batch" then
    --> [Yes] "Batch Mode"
    -> [Extract Batch] "Message Set"
    --> [Checkout (Track)] "AsyncContext<m>"
    "AsyncContext<m>" --> [Process] "Acknowledge Async Processing"
    note bottom
        Each message has an exposed function to mark it as processed.
    end note
    --> [Remove] "Message Set"
    "Message Set" -> [Maintain Until Empty] (*)
else
    --> [No] "SyncContext<m>"
    "SyncContext<m>" -> [Process] "Acknowledge Sync Processing"
    --> (*)
@endumlcc